import = [".config/dracula.toml"]

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "Semibold"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "None"
startup_mode = "Maximized"

[window.dimensions]
columns = 140
lines = 30

[window.padding]
x = 2
y = 2

[mouse]
hide_when_typing = true
